import csv, hashlib, json, re, urllib.request
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIELDS = (ROOT / "METADATA" / "manifest_fields.txt").read_text().splitlines()

SOURCES = [
 dict(id="INT-UN-CHARTER-1945", domain="INTERNATIONAL", slug="un_charter_1945", title="Charter of the United Nations and Statute of the International Court of Justice", org="United Nations", dt="1945-06-26", country="International", st="treaty", sub="founding treaty", topics="multilateral negotiation;international organization;collective security", case="San Francisco Conference", participants="United Nations member states", url="https://treaties.un.org/doc/publication/ctc/uncharter.pdf", fmt="PDF", doc="UN Charter", notes="Official UN Treaty Collection PDF."),
 dict(id="INT-UN-VCLT-1969", domain="INTERNATIONAL", slug="vienna_convention_law_treaties_1969", title="Vienna Convention on the Law of Treaties", org="United Nations", dt="1969-05-23", country="International", st="treaty", sub="treaty law", topics="treaty negotiation;interpretation;ratification;reservations", case="Vienna Conference on the Law of Treaties", participants="States Parties", url="https://legal.un.org/ilc/texts/instruments/english/conventions/1_1_1969.pdf", fmt="PDF", doc="A/CONF.39/27", notes="Official UN Office of Legal Affairs text."),
 dict(id="INT-WTO-MARRAKESH-1994", domain="INTERNATIONAL", slug="wto_marrakesh_agreement_1994", title="Marrakesh Agreement Establishing the World Trade Organization", org="World Trade Organization", dt="1994-04-15", country="International", st="trade agreement", sub="multilateral trade", topics="Uruguay Round;institution building;trade negotiation", case="Uruguay Round", participants="WTO members", url="https://www.wto.org/english/docs_e/legal_e/04-wto.pdf", fmt="PDF", doc="WTO Agreement", notes="Official WTO legal text PDF."),
 dict(id="INT-WTO-GATT-1994", domain="INTERNATIONAL", slug="gatt_1994", title="General Agreement on Tariffs and Trade 1994", org="World Trade Organization", dt="1994-04-15", country="International", st="trade agreement", sub="goods trade", topics="tariffs;concessions;trade negotiation;safeguards", case="Uruguay Round", participants="WTO members", url="https://www.wto.org/english/docs_e/legal_e/06-gatt.pdf", fmt="PDF", doc="GATT 1994", notes="Official WTO legal text PDF."),
 dict(id="INT-WTO-TRIPS-1994", domain="INTERNATIONAL", slug="wto_trips_agreement_1994", title="Agreement on Trade-Related Aspects of Intellectual Property Rights", org="World Trade Organization", dt="1994-04-15", country="International", st="trade agreement", sub="intellectual property", topics="intellectual property;licensing;trade negotiation;enforcement", case="Uruguay Round", participants="WTO members", url="https://www.wto.org/english/docs_e/legal_e/27-trips.pdf", fmt="PDF", doc="TRIPS", notes="Official WTO legal text PDF."),
 dict(id="INT-WTO-DSU-1994", domain="LEGAL", slug="wto_dispute_settlement_understanding_1994", title="Understanding on Rules and Procedures Governing the Settlement of Disputes", org="World Trade Organization", dt="1994-04-15", country="International", st="dispute settlement agreement", sub="international dispute resolution", topics="consultation;mediation;settlement;arbitration;implementation", case="Uruguay Round", participants="WTO members", url="https://www.wto.org/english/docs_e/legal_e/28-dsu.pdf", fmt="PDF", doc="DSU", notes="Official WTO legal text PDF."),
 dict(id="LAB-ILO-CB-GUIDE-2015", domain="LABOR", slug="ilo_collective_bargaining_policy_guide_2015", title="Collective Bargaining: A Policy Guide", org="International Labour Organization", dt="2015-01-01", country="International", st="institutional guide", sub="collective bargaining", topics="collective bargaining;labor negotiation;dispute prevention;implementation", case="", participants="governments;employers;workers organizations", url="https://www.ilo.org/sites/default/files/wcmsp5/groups/public/%40ed_protect/%40protrav/%40travail/documents/instructionalmaterial/wcms_425004.pdf", fmt="PDF", doc="ISBN 978-92-2-129232-6", notes="Official ILO open web PDF; secondary institutional guidance with model processes.", primary="FALSE", secondary="TRUE"),
 dict(id="VC-NVCA-LIFESCI-TS-2022", domain="VC", slug="nvca_life_science_license_term_sheet_2022", title="Model Term Sheet for University Life Science Startup License", org="National Venture Capital Association", dt="2022-11-19", country="United States", st="model term sheet", sub="life-science venture licensing", topics="term sheet;university licensing;equity;royalties;milestones;sublicensing", case="US-BOLT Life Science", participants="universities;venture capital firms;startup licensees", url="https://nvca.org/wp-content/uploads/2022/11/TTO-and-VC-Early-Stage-Life-Science-Term-Sheet-11-19-22-launch.pdf", fmt="PDF", doc="US-BOLT Life Science", notes="Freely downloadable official NVCA model document."),
 dict(id="VC-NVCA-CLIMATE-TS-2024", domain="VC", slug="nvca_climate_license_term_sheet_2024", title="University Startup Basic Outlicense Template: Climate, Environment and Sustainability-Related Tech", org="National Venture Capital Association", dt="2024-04-04", country="United States", st="model term sheet", sub="climate-tech venture licensing", topics="term sheet;university licensing;equity;royalties;milestones;sublicensing", case="US-BOLT Climate", participants="universities;venture capital firms;startup licensees", url="https://nvca.org/wp-content/uploads/2024/04/US-BOLT-Term-Sheet-Climate-final-4-4-24.pdf", fmt="PDF", doc="US-BOLT Climate", notes="Freely downloadable official NVCA model document."),
 dict(id="MA-LINKEDIN-MSFT-2016", domain="MA", slug="linkedin_microsoft_definitive_proxy_2016", title="LinkedIn Definitive Proxy Statement: Microsoft Merger", org="LinkedIn Corporation; U.S. Securities and Exchange Commission", dt="2016-07-22", country="United States", st="SEC merger proxy", sub="technology M&A", topics="auction;offers;counteroffers;exclusivity;termination fee;board process", case="Microsoft acquisition of LinkedIn", participants="Microsoft;LinkedIn;Party A;Qatalyst Partners", url="https://www.sec.gov/Archives/edgar/data/1271024/000104746916014430/a2229104zdefm14a.htm", fmt="HTML", doc="SEC 0001047469-16-014430", notes="Official EDGAR filing; contains detailed background of merger and annexed merger agreement."),
 dict(id="MA-TWITTER-MUSK-2022", domain="MA", slug="twitter_musk_definitive_proxy_2022", title="Twitter Definitive Proxy Statement: Musk Merger", org="Twitter, Inc.; U.S. Securities and Exchange Commission", dt="2022-07-26", country="United States", st="SEC merger proxy", sub="technology M&A", topics="unsolicited offer;board process;merger negotiation;financing;termination", case="Elon Musk acquisition of Twitter", participants="Twitter;Elon Musk;Morgan Stanley", url="https://www.sec.gov/Archives/edgar/data/1418091/000119312522202163/d283119ddefm14a.htm", fmt="HTML", doc="SEC 0001193125-22-202163", notes="Official EDGAR filing; contains chronology and merger agreement."),
 dict(id="MA-FITBIT-GOOGLE-2019", domain="MA", slug="fitbit_google_definitive_proxy_2019", title="Fitbit Definitive Proxy Statement: Google Merger", org="Fitbit, Inc.; U.S. Securities and Exchange Commission", dt="2019-12-12", country="United States", st="SEC merger proxy", sub="technology M&A", topics="strategic alternatives;bidding;offers;board process;merger agreement", case="Google acquisition of Fitbit", participants="Fitbit;Google;other bidders", url="https://www.sec.gov/Archives/edgar/data/1447599/000162828019015006/fitbitdefinitiveproxy.htm", fmt="HTML", doc="SEC 0001628280-19-015006", notes="Official EDGAR filing; contains detailed sale process and agreement terms."),
 dict(id="PHARMA-PFIZER-BNTX-2020", domain="PHARMA", slug="pfizer_biontech_collaboration_agreement_2020", title="Collaboration Agreement between Pfizer Inc. and BioNTech SE", org="BioNTech SE; U.S. Securities and Exchange Commission", dt="2020-03-17", country="United States;Germany", st="filed collaboration agreement", sub="pharmaceutical licensing", topics="co-development;commercialization;licensing;governance;cost sharing;termination", case="Pfizer-BioNTech COVID-19 vaccine collaboration", participants="Pfizer;BioNTech", url="https://www.sec.gov/Archives/edgar/data/1776985/000119312520195911/d939702dex1045.htm", fmt="HTML", doc="SEC Exhibit 10.45", notes="Official EDGAR exhibit; limited redactions marked in filing."),
]

def download(url, target):
    req = urllib.request.Request(url, headers={"User-Agent":"NegotiationCorpus research contact corpus@example.org", "Accept":"*/*"})
    with urllib.request.urlopen(req, timeout=90) as r:
        data = r.read()
    target.write_bytes(data)
    return data

def pdf_pages(data):
    return len(re.findall(br"/Type\s*/Page\b", data))

rows=[]
for s in SOURCES:
    outdir = ROOT / s["domain"] / s["slug"]
    outdir.mkdir(parents=True, exist_ok=True)
    ext = ".pdf" if s["fmt"] == "PDF" else ".html"
    target = outdir / ("original" + ext)
    data = download(s["url"], target)
    sig_ok = data.startswith(b"%PDF-") if s["fmt"] == "PDF" else (b"<html" in data[:1000].lower() or b"<!doctype" in data[:1000].lower())
    if not sig_ok: raise RuntimeError(f"Bad signature for {s['id']}: {data[:80]!r}")
    sha = hashlib.sha256(data).hexdigest()
    text = re.sub(r"<[^>]+>", " ", data.decode("utf-8", "ignore")) if s["fmt"] == "HTML" else ""
    row={k:"" for k in FIELDS}
    row.update(SOURCE_ID=s["id"], TITLE=s["title"], ORGANIZATION=s["org"], DATE=s["dt"], YEAR=s["dt"][:4], LANGUAGE="English", COUNTRY=s["country"], SOURCE_TYPE=s["st"], DOMAIN=s["domain"], SUBDOMAIN=s["sub"], TOPICS=s["topics"], CASE_NAME=s["case"], PARTICIPANTS=s["participants"], URL=s["url"], DOCUMENT_NUMBER=s["doc"], FILE_PATH=target.relative_to(ROOT.parent).as_posix(), FILE_FORMAT=s["fmt"], PAGE_COUNT=str(pdf_pages(data)) if s["fmt"]=="PDF" else "", WORD_COUNT=str(len(re.findall(r"\b\w+\b", text))) if text else "", PRIMARY_SOURCE=s.get("primary","TRUE"), SECONDARY_SOURCE=s.get("secondary","FALSE"), ORIGINAL_SOURCE="TRUE", HOST_SOURCE=s["org"].split(";")[-1].strip(), ACCESS_DATE=str(date.today()), ACCESS_STATUS="ACQUIRED", COPYRIGHT_STATUS="Publicly accessible official document; rights retained by issuing body where applicable", LICENSE="Official public access; no license inference", TRAINING_PERMISSION="REVIEW_REQUIRED", PROVENANCE=f"Downloaded directly from official host on {date.today()}; native file preserved unchanged", RELIABILITY_SCORE="5", TRAINING_VALUE="5" if s.get("primary","TRUE")=="TRUE" else "4", UNIQUENESS_SCORE="4", CASE_VALUE="5" if s["domain"] in ("MA","PHARMA") else "4", TRANSCRIPT_VALUE="0", SOURCE_QUALITY="5", OCR_REQUIRED="FALSE", OCR_QUALITY="N/A", DUPLICATE_STATUS="UNIQUE_IN_BATCH", NOTES=s["notes"], SHA256=sha, FILE_SIZE_BYTES=str(len(data)), AUTHORITY="5", PRIMARY_SOURCE_VALUE="5" if s.get("primary","TRUE")=="TRUE" else "2", RELIABILITY="5", NEGOTIATION_RELEVANCE="5", INFORMATION_DENSITY="5", CASE_DETAIL="5" if s["domain"] in ("MA","PHARMA") else "3", TACTICAL_DETAIL="5" if s["domain"]=="MA" else "3", STRATEGIC_DETAIL="5" if s["domain"]=="MA" else "4", OUTCOME_VISIBILITY="5", COUNTERPARTY_VISIBILITY="4", UNIQUENESS="4")
    (outdir / "metadata.json").write_text(json.dumps(row, indent=2, ensure_ascii=False)+"\n", encoding="utf-8")
    rows.append(row)

batch=ROOT/"METADATA"/"batches"/"international_commercial.csv"
batch.parent.mkdir(parents=True,exist_ok=True)
with batch.open("w",newline="",encoding="utf-8-sig") as f:
    w=csv.DictWriter(f,fieldnames=FIELDS); w.writeheader(); w.writerows(rows)
print(f"Acquired {len(rows)} documents; {sum(int(r['FILE_SIZE_BYTES']) for r in rows)} bytes")
